# Generated by Django 4.2.4 on 2023-09-11 13:26

from django.conf import settings
from django.db import migrations


def create_superuser(apps, editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    User.objects.create_superuser(username='admin',
                                  email='admin@django_diploma.test',
                                  password='123456')
    user_1 = User.objects.create(username='user_1', password='123456')
    user_2 = User.objects.create(username='user_2', password='123456')
    user_3 = User.objects.create(username='user_3', password='123456')
    user_4 = User.objects.create(username='user_4', password='123456')
    user_5 = User.objects.create(username='user_5', password='123456')
    user_6 = User.objects.create(username='user_6', password='123456')

    Group = apps.get_model("auth", "Group")
    buyers = Group.objects.create(name="Buyers")
    buyers.user_set.add(user_1)
    buyers.user_set.add(user_2)
    buyers.user_set.add(user_3)
    sellers = Group.objects.create(name="Sellers")
    sellers.user_set.add(user_4)
    sellers.user_set.add(user_5)
    sellers.user_set.add(user_6)


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(create_superuser, migrations.RunPython.noop),
    ]
