# Generated by Django 4.2.4 on 2023-09-21 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myapi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип доставки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена')),
                ('is_free_from', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Бесплатно с:')),
            ],
            options={
                'verbose_name': 'Тип доставки',
                'verbose_name_plural': 'Типы доставки',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(blank=True, max_length=200)),
                ('src', models.ImageField(upload_to=myapi.models.Image.image_directory_path)),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ('alt', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('payment_type', models.CharField(blank=True, default='online', max_length=150, verbose_name='Тип оплаты')),
                ('status', models.CharField(blank=True, default='created', max_length=150, verbose_name='Состояние заказа')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес доставки')),
                ('delivery_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapi.delivery', verbose_name='Тип доставки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Автор')),
                ('email', models.CharField(blank=True, max_length=320, verbose_name='Электронная почта')),
                ('text', models.TextField(blank=True, verbose_name='Содержание')),
                ('rate', models.PositiveSmallIntegerField(default=0, verbose_name='Оценка')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('author',),
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('value', models.TextField(blank=True, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Спецификация',
                'verbose_name_plural': 'Спецификации',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionID', models.CharField(blank=True, max_length=250, verbose_name='Идентификатор сессии')),
            ],
            options={
                'verbose_name': 'Пользовательская сессия',
                'verbose_name_plural': 'Пользовательские сессии',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(blank=True, max_length=500)),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myapi.image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профиля',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Наименование')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='Краткое описание')),
                ('freeDelivery', models.BooleanField(default=False, verbose_name='Бесплатная доставка')),
                ('limited_edition', models.BooleanField(default=False, verbose_name='Ограниченный тираж')),
                ('fullDescription', models.TextField(blank=True, verbose_name='Полное описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapi.catalogitem', verbose_name='Категория')),
                ('images', models.ManyToManyField(blank=True, related_name='products', to='myapi.image', verbose_name='Изображения')),
                ('reviews', models.ManyToManyField(blank=True, related_name='products', to='myapi.review', verbose_name='Отзывы')),
                ('specifications', models.ManyToManyField(blank=True, related_name='products', to='myapi.specification', verbose_name='Спецификации')),
                ('tags', models.ManyToManyField(blank=True, related_name='products', to='myapi.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapi.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapi.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Строка заказа',
                'verbose_name_plural': 'Строки заказа',
            },
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapi.image'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='myapi.catalogitem'),
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapi.product', verbose_name='Товар')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapi.usersession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
    ]
